# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies (skip prepare scripts, will build explicitly)
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Build the project
RUN npm run build

# Expose any necessary ports (if needed, MCP usually uses stdio so port not required)

# Command to run the MCP server
CMD ["node", "build/index.js", "--stdio"]
